local keymap = vim.keymap.set
keymap("n", "<F9>", "<Esc>:Neotree toggle<CR>", { silent = true })
keymap("n", "<F8>", "<Esc>:CocCommand document.toggleInlayHint<CR>", { silent = true })
keymap("n", "<F10>", "<cmd>BearMake<CR>")
keymap("n", "<leader>cc", "<cmd>BearMake<CR>")
keymap("n", "q:", "<nop>")
keymap("n", "q/", "<nop>")
keymap("n", "<C-Up>", "<cmd>resize +2<CR>")
keymap("n", "<C-Down>", "<cmd>resize -2<CR>")
keymap("n", "<C-Left>", "<cmd>vertical resize -2<CR>")
keymap("n", "<C-Right>", "<cmd>vertical resize +2<CR>")
